version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0 
    working_directory: ~/project/src 
    steps:
      - checkout
      - run: npm cache clean --force 
      - run: git submodule update --init --recursive src/libs
      - run: mkdir -p opt/content && cp -r src/* opt/content/
      - restore_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
      - run: cd opt/content/ && npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
          paths: ./node_modules     
      - run: cd opt && zip -r content.zip content
      - store_artifacts:
          path: opt/content.zip 
          destination: content.zip  
      - run:
          name: Run test cases
          command: 'cd src && npm install --unsafe-perm && npm run coverage'     
      - run:
          name: install sonar scanner
          command: |
            cd ~/project && mkdir -p /tmp
            cd /tmp
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip || sudo apt install unzip -y
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            cd -
      - run:
         name: run sonar scanner
         command: 'cd ~/project && /tmp/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner'
                  
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
