version: 2.1
jobs:
  build:
    docker:
      - image: node:6-alpine
    steps:
      - checkout
      - run: apk add zip git
      - run: apk add python make g++
      #- run: git submodule update --init --recursive src/libs
      - run: git submodule update --init
      - run: git submodule update --init --recursive --remote
      - run: mkdir -p opt/content && cp -r src/* opt/content/
      #- restore_cache:
          #key: dependency-cache-{{ checksum "package.json" }}
      - run: cd opt/content/ && npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      #- run: cd opt && zip -r content.zip content
      
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
