version: 2.1
jobs:
  build:
    docker:
      - image: node:6-alpine
    steps:
      - checkout
      - run: apk add zip git
      - run: apk add python make g++
      - run: git submodule update --init --recursive src/libs
      - run: mkdir -p opt/content && cp -r src/* opt/content/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: cd opt/content/ && npm install --unsafe-perm
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run: cd opt && zip -r content.zip content
      - store_artifacts:
          path: opt/content.zip 
          destination: content.zip
      - run: 
          name: Install sonar scanner
          command: 'npm install -g sonarqube-scanner'
          
      - run: 
          name: Sonar scanner
          command: |
             sonar-scanner -Dsonar.projectKey=project-sunbird_sunbird-content-service -Dsonar.organization=project-sunbird -Dsonar.projectName=sunbird-content-service -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.language=js

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
